--- 
services: 
  jenkinsdata: 
    build: 
      context: "."
      dockerfile: Dockerfile-data
  jenkinsmaster: 
    build: 
      context: "."
      dockerfile: Dockerfile
    ports: 
      - "50000:50000"
      - "8080:8080"
    volumes_from: 
      - jenkinsdata
version: "2"
